# FILE MOSTLY GENERATED BY AI

import pandas as pd

# Load GTFS files
assetDir = '../assets/trains/routes/'
routes = pd.read_csv(assetDir + 'routes.txt')
trips = pd.read_csv(assetDir + 'trips.txt')
stop_times = pd.read_csv(assetDir + 'stop_times.txt')
stops = pd.read_csv(assetDir + 'stops.txt')

trainLinesWithIcons = ["1", "2", "3", "4", "5", "6", "7", "7d", "a", "b", "c", "d", "e", "f", "g", "h", "j", "l", "m", "n", "q", "r", "s", "sf", "sir", "sr", "w", "z"]

for currentTrain in trainLinesWithIcons:
    # Filter for the 1 train route
    route = routes[routes['route_short_name'] == currentTrain]

    # Get trips for the 1 train
    trips = trips[trips['route_id'].isin(route['route_id'])]

    # Get stop times for the 1 train trips
    stop_times = stop_times[stop_times['trip_id'].isin(trips['trip_id'])]

    # Get stop details for the 1 train stops
    stops = stops[stops['stop_id'].isin(stop_times['stop_id'])]

    # Merge stop times with stop details
    route_stops = pd.merge(stop_times, stops, on='stop_id')

    # Select relevant columns and sort by trip and stop sequence
    route_stops = route_stops[['trip_id', 'stop_id', 'stop_name', 'stop_lat', 'stop_lon', 'stop_sequence']]
    route_stops = route_stops.sort_values(by=['trip_id', 'stop_sequence'])

    # Write to a txt file
    route_stops.to_csv(f"stops-{currentTrain}.txt", index=False)

    print(f"Route information for the {currentTrain} train has been written to 'route_stops.csv'")
